dist: bionic
language: scala

notifications:
  slack:
    rooms:
      - secure: "CvzjIkQaOFzxiP005WTLazd751qxDz6B3jvUesv/e+16AKlyuyGV0P9lJs527++xut7ZoZKtTibVI9b8wGAWUBFvMD9OBjxzyAzbBE8QE+c7B/GkoWwjTNqMWSyXgXIYL01C2vMeK0PEzpQTWFdNrxu3Psrxx2EXxT6swDlbAV9BAxqaElCn3U4uZSmzfa0ZKKfXRNG/AhVAd0eUr5gdXobh/D/iuGWrZC/niHNtZyZxtCiWftX7j2u0UCgOP9pDmOmdRELMQHm7fyKwZM2JGLNAnEtmQnJU3rBtj2USDr7qjc9QkbRqmy7E777AwJGeoeHpLldRqw2UEkfiO8fhLvhDvdW4L+FgrivDayPA462UBOnu8x2mAVgLHQIJ1ifCK1JkJjY0diW3bUaGrD8Yhpz7rIGUQToqXA9x/309DfhvtV9OdB5eAb9Gqm1uZxv2uogieaolH72bKtNJgHt9Wwb8duyr/rUBCmm78N9r6dD9rpv7L2yNQZ/ft4sRS0NpRu7YAm5P9iyH/Nz60FpW6K9Awer35PKBhloO3ua1ObSlKIDg19gLczfG9JKL5usrmUZUkAK1+81Gb1npOeoeSXmUVNDmtRve1p0T4LlGZpZJoXFCSoKdouz2/XdxTVMY4ml10SbS5zf7oqw7PvBdt/cAijE8otR9R927ImxeyLg="
    on_success: always
    on_failure: always

scala:
  - 2.13.3

jdk:
  - openjdk11

cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt/boot
    - $HOME/.coursier

install:
  - sudo apt-get install python3.6 rng-tools haveged
  - sudo haveged

jobs:
  include:
    - stage: test
      script:
        - ./make test
    - stage: ittest
      script:
        - ./make itest

branches:
  only:
  - master

stages:
  - test
  - ittest
