name: Integration-Test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  itest:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [ 11 ]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java }}
      - run: sudo apt-get install rng-tools haveged
      - run: ./make itest
