name: Unit-Test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]
        java: [ 8, 11 ]
    steps:
      - uses: actions/checkout@v2
      - uses: olafurpg/setup-scala@v10
        with:
          java-version: ${{ matrix.java }}
      - name: Install rgn tools for linux
        if: ${{ matrix.os == 'ubuntu-latest' }}
        run: sudo apt-get install rng-tools haveged
      - run: sbt coverage test coverageReport
        shell: bash
